[package]
name = "cli_derive"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"
# 过程宏
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.23"
syn = {version="1.0.107", features=["full"]}
